/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface StreamingInterface extends utils.Interface {
  functions: {
    "balanceOf(uint256,address)": FunctionFragment;
    "cancelStream(uint256)": FunctionFragment;
    "createStream(address,uint256,uint256,uint256)": FunctionFragment;
    "getStream(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "streamIdCounter()": FunctionFragment;
    "withdrawFromStream(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "balanceOf"
      | "cancelStream"
      | "createStream"
      | "getStream"
      | "owner"
      | "streamIdCounter"
      | "withdrawFromStream"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelStream",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createStream",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getStream",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "streamIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromStream",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStream", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "streamIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromStream",
    data: BytesLike
  ): Result;

  events: {
    "CancelStream(uint256,address,address,uint256,uint256)": EventFragment;
    "CreateStream(uint256,address,address,uint256,uint256,uint256)": EventFragment;
    "WithdrawFromStream(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CancelStream"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateStream"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawFromStream"): EventFragment;
}

export interface CancelStreamEventObject {
  streamId: BigNumber;
  sender: string;
  recipient: string;
  vestedAmount: BigNumber;
  remainingAmount: BigNumber;
}
export type CancelStreamEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber],
  CancelStreamEventObject
>;

export type CancelStreamEventFilter = TypedEventFilter<CancelStreamEvent>;

export interface CreateStreamEventObject {
  streamId: BigNumber;
  sender: string;
  recipient: string;
  deposit: BigNumber;
  startTime: BigNumber;
  stopTime: BigNumber;
}
export type CreateStreamEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber, BigNumber],
  CreateStreamEventObject
>;

export type CreateStreamEventFilter = TypedEventFilter<CreateStreamEvent>;

export interface WithdrawFromStreamEventObject {
  streamId: BigNumber;
  recipient: string;
}
export type WithdrawFromStreamEvent = TypedEvent<
  [BigNumber, string],
  WithdrawFromStreamEventObject
>;

export type WithdrawFromStreamEventFilter =
  TypedEventFilter<WithdrawFromStreamEvent>;

export interface Streaming extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StreamingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    balanceOf(
      streamId: PromiseOrValue<BigNumberish>,
      who: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    cancelStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createStream(
      recipient: PromiseOrValue<string>,
      deposit: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      stopTime: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        sender: string;
        recipient: string;
        deposit: BigNumber;
        balance: BigNumber;
        startTime: BigNumber;
        stopTime: BigNumber;
        rate: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    streamIdCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    withdrawFromStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  balanceOf(
    streamId: PromiseOrValue<BigNumberish>,
    who: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  cancelStream(
    streamId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createStream(
    recipient: PromiseOrValue<string>,
    deposit: PromiseOrValue<BigNumberish>,
    startTime: PromiseOrValue<BigNumberish>,
    stopTime: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getStream(
    streamId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      sender: string;
      recipient: string;
      deposit: BigNumber;
      balance: BigNumber;
      startTime: BigNumber;
      stopTime: BigNumber;
      rate: BigNumber;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  streamIdCounter(overrides?: CallOverrides): Promise<BigNumber>;

  withdrawFromStream(
    streamId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    balanceOf(
      streamId: PromiseOrValue<BigNumberish>,
      who: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createStream(
      recipient: PromiseOrValue<string>,
      deposit: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      stopTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        sender: string;
        recipient: string;
        deposit: BigNumber;
        balance: BigNumber;
        startTime: BigNumber;
        stopTime: BigNumber;
        rate: BigNumber;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    streamIdCounter(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawFromStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CancelStream(uint256,address,address,uint256,uint256)"(
      streamId?: PromiseOrValue<BigNumberish> | null,
      sender?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      vestedAmount?: null,
      remainingAmount?: null
    ): CancelStreamEventFilter;
    CancelStream(
      streamId?: PromiseOrValue<BigNumberish> | null,
      sender?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      vestedAmount?: null,
      remainingAmount?: null
    ): CancelStreamEventFilter;

    "CreateStream(uint256,address,address,uint256,uint256,uint256)"(
      streamId?: PromiseOrValue<BigNumberish> | null,
      sender?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      deposit?: null,
      startTime?: null,
      stopTime?: null
    ): CreateStreamEventFilter;
    CreateStream(
      streamId?: PromiseOrValue<BigNumberish> | null,
      sender?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      deposit?: null,
      startTime?: null,
      stopTime?: null
    ): CreateStreamEventFilter;

    "WithdrawFromStream(uint256,address)"(
      streamId?: PromiseOrValue<BigNumberish> | null,
      recipient?: PromiseOrValue<string> | null
    ): WithdrawFromStreamEventFilter;
    WithdrawFromStream(
      streamId?: PromiseOrValue<BigNumberish> | null,
      recipient?: PromiseOrValue<string> | null
    ): WithdrawFromStreamEventFilter;
  };

  estimateGas: {
    balanceOf(
      streamId: PromiseOrValue<BigNumberish>,
      who: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createStream(
      recipient: PromiseOrValue<string>,
      deposit: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      stopTime: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    streamIdCounter(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawFromStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balanceOf(
      streamId: PromiseOrValue<BigNumberish>,
      who: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createStream(
      recipient: PromiseOrValue<string>,
      deposit: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      stopTime: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    streamIdCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawFromStream(
      streamId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
